<a href="https://colab.research.google.com/github/osmdwight/Data-Science/blob/main/step348.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

"""
import matplotlib.pyplot as plt

# key and value pair
genres = {
    "Mystery": 20,
    "Western": 18,
    "Non Fiction": 35,
    "Fiction": 20,
    "Teen Fiction": 15,
    "Biography": 22,
    "Science": 15,
    "Math": 25
}

x = []
y = []
genre_names = list(genres.keys())

for i, genre in enumerate(genre_names):
    count = genres[genre]
    for j in range(count):
        x.append(i)
        y.append(j + 1)

plt.scatter(x, y)

plt.xticks(range(len(genre_names)), genre_names, rotation=45)
plt.ylabel("Number of Books")
plt.xlabel("Genre")
plt.title("Dot Plot of Books by Genre")

plt.tight_layout()
plt.show()

"""

'\nimport matplotlib.pyplot as plt\n\n# key and value pair\ngenres = {\n    "Mystery": 20,\n    "Western": 18,\n    "Non Fiction": 35,\n    "Fiction": 20,\n    "Teen Fiction": 15,\n    "Biography": 22,\n    "Science": 15,\n    "Math": 25\n}\n\nx = []\ny = []\ngenre_names = list(genres.keys())\n\nfor i, genre in enumerate(genre_names):\n    count = genres[genre]\n    for j in range(count):\n        x.append(i)\n        y.append(j + 1)\n\nplt.scatter(x, y)\n\nplt.xticks(range(len(genre_names)), genre_names, rotation=45)\nplt.ylabel("Number of Books")\nplt.xlabel("Genre")\nplt.title("Dot Plot of Books by Genre")\n\nplt.tight_layout()\nplt.show()\n\n'

In [1]:
"""

import matplotlib.pyplot as plt
from scipy import stats


x=[90,50,60,70,62,55,58,60]
y=[180,178,179,177,180,179,177,176]

slope, intercept, r, p, std_err = stats.linregress(x, y)

def myfunc(x):
  return slope * x + intercept

mymodel = list(map(myfunc, x))

plt.scatter(x,y)
plt.plot(x, mymodel)
plt.title("Scatter Plot of Height and Weight")
plt.xlabel("Weight")
plt.ylabel("Height")
plt.show()


"""

'\n\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\n\nx=[90,50,60,70,62,55,58,60]\ny=[180,178,179,177,180,179,177,176]\n\nslope, intercept, r, p, std_err = stats.linregress(x, y)\n\ndef myfunc(x):\n  return slope * x + intercept\n\nmymodel = list(map(myfunc, x))\n\nplt.scatter(x,y)\nplt.plot(x, mymodel)\nplt.title("Scatter Plot of Height and Weight")\nplt.xlabel("Weight")\nplt.ylabel("Height")\nplt.show()\n\n\n'

In [10]:
import pandas as pd

#importing the file  using pandas

df=pd.read_csv("/content/Realestate.csv")
df.head()

,No,transaction,houseAge,distanceToNearestMRTstation,numberOfConvenienceStores,latitude,longitude,housePriceOfUnitArea
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,NaN
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [12]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#normalizing using a built in function

df['houseAgeStandardized'] = MinMaxScaler().fit_transform(np.array(df['houseAge']).reshape(-1,1))

#dropping the column using .drop()
df.drop(columns=['numberOfConvenienceStores'], inplace=True)


df.head()

,No,transaction,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,32.0,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,19.5,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,13.3,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,13.3,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,5.0,390.56840,24.97937,121.54245,43.1,0.114155

In [13]:
df=df.rename(columns={'transaction':'transactionDate'}) #renaming the column
df.head()

,No,transactionDate,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,32.0,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,19.5,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,13.3,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,13.3,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,5.0,390.56840,24.97937,121.54245,43.1,0.114155

In [16]:
df.loc[0:10,:] #displaying first 10 rows and all columns

,No,transactionDate,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,32.0,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,19.5,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,13.3,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,13.3,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,5.0,390.56840,24.97937,121.54245,43.1,0.114155
5,6,2012.667,7.1,2175.03000,24.96305,121.51254,32.1,0.162100
6,7,2012.667,34.5,623.47310,24.97933,121.53642,40.3,0.787671
7,8,2013.417,20.3,287.60250,24.98042,121.54228,46.7,0.463470
8,9,2013.500,31.7,5512.03800,24.95095,121.48458,18.8,0.723744
9,10,2013.417,17.9,1783.18000,24.96731,121.51486,22.1,0.408676
10,11,2013.083,34.8,405.21340,24.97349,121.53372,41.4,0.794521

In [17]:
df.iloc[:10] #displaying the first 10 rows

,No,transactionDate,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,32.0,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,19.5,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,13.3,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,13.3,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,5.0,390.56840,24.97937,121.54245,43.1,0.114155
5,6,2012.667,7.1,2175.03000,24.96305,121.51254,32.1,0.162100
6,7,2012.667,34.5,623.47310,24.97933,121.53642,40.3,0.787671
7,8,2013.417,20.3,287.60250,24.98042,121.54228,46.7,0.463470
8,9,2013.500,31.7,5512.03800,24.95095,121.48458,18.8,0.723744
9,10,2013.417,17.9,1783.18000,24.96731,121.51486,22.1,0.408676

In [18]:
len(df.duplicated()) #checking for duplicated values

418

In [19]:
df=df.drop_duplicates(keep='first') #dropping duplicatted values

In [22]:
df.isna().sum() #checking null values

No                             0
transactionDate                0
houseAge                       0
distanceToNearestMRTstation    0
latitude                       0
longitude                      0
housePriceOfUnitArea           3
houseAgeStandardized           0
dtype: int64

In [26]:
mean_value = df['housePriceOfUnitArea'].mean()  #filling it in using mean (missings)
df['housePriceOfUnitArea'].fillna(mean_value, inplace=True)

/tmp/ipykernel_148/4017303039.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['housePriceOfUnitArea'].fillna(mean_value, inplace=True)
/tmp/ipykernel_148/4017303039.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['housePriceOfUnitArea'].fillna(mean_value, inplace=True)